const VERSION='0.1.1';
const riskRank={read:1,network:2,write:3,money:4,destructive:5};
const fallbackTools=[{id:'registry.search',name:'RegistrySearch',description:'Search the live AFO tool registry for tools and child agents by capability.',capabilities:['discover tools','search tool registry','find child agents','list capabilities'],permissions:['registry:read'],environment:'worker',risk:'read',version:VERSION,inputSchema:'capability:string,riskMax?:ToolRisk',outputSchema:'matches:ToolManifest[]'},{id:'cloudflare.worker.deployPlan',name:'CloudflareWorkerDeployPlan',description:'Create a safe deployment plan for a Cloudflare Worker without deploying it.',capabilities:['plan cloudflare worker','edge worker planning','deployment planning'],permissions:['cloudflare:plan'],environment:'cloudflare',risk:'read',version:VERSION,inputSchema:'workerName:string,purpose:string',outputSchema:'workerName:string,steps:string[]'},{id:'afo.agent.status',name:'AfoAgentStatus',description:'Return AFO.Agent gateway status and runtime shape.',capabilities:['agent status','gateway status','health check'],permissions:['agent:read'],environment:'worker',risk:'read',version:VERSION,inputSchema:'{}',outputSchema:'status object'}];
const leadAgent={id:'agent.afo.lead',name:'AFO Lead Agent',mission:'Unify agents, tools, registries, and execution environments through safe discovery, policy checks, gateway execution, and receipts.',allowedEnvironments:['local','cloudflare','github','browser','container','mcp','worker'],maxRisk:'write',requiredReceipts:true};
function json(data,init={}){return new Response(JSON.stringify(data,null,2),{...init,headers:{'content-type':'application/json; charset=utf-8',...(init.headers||{})}})}
async function readJson(request){try{return await request.json()}catch{return {}}}
async function dbTools(env){if(!env.AFO_DB)return fallbackTools;try{const res=await env.AFO_DB.prepare('SELECT manifest_json FROM tools ORDER BY id').all();const rows=res.results||[];if(!rows.length)return fallbackTools;return rows.map(r=>JSON.parse(r.manifest_json))}catch{return fallbackTools}}
async function dbReceipts(env,limit=50){if(!env.AFO_DB)return [];try{const res=await env.AFO_DB.prepare('SELECT * FROM receipts ORDER BY created_at DESC LIMIT ?').bind(limit).all();return res.results||[]}catch{return []}}
async function writeReceipt(env,item){const receipt={id:crypto.randomUUID(),requestId:item.requestId,agentId:leadAgent.id,toolId:item.toolId,purpose:item.purpose,status:item.status,reason:item.reason||null,input:item.input??null,output:item.output??null,error:item.error||null,createdAt:new Date().toISOString()};if(env.AFO_DB){await env.AFO_DB.prepare('INSERT INTO receipts (id,request_id,agent_id,tool_id,purpose,status,reason,input_json,output_json,error,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(receipt.id,receipt.requestId,receipt.agentId,receipt.toolId,receipt.purpose,receipt.status,receipt.reason,JSON.stringify(receipt.input),JSON.stringify(receipt.output),receipt.error,receipt.createdAt).run()}if(env.AFO_ARTIFACTS){await env.AFO_ARTIFACTS.put(`receipts/${receipt.createdAt.slice(0,10)}/${receipt.id}.json`,JSON.stringify(receipt,null,2),{httpMetadata:{contentType:'application/json'}})}return receipt}
function searchTools(tools,query={}){const capability=String(query.capability||'').toLowerCase();const riskMax=query.riskMax;return tools.filter(t=>{const cap=!capability||t.name.toLowerCase().includes(capability)||t.description.toLowerCase().includes(capability)||(t.capabilities||[]).some(c=>c.toLowerCase().includes(capability));const risk=!riskMax||riskRank[t.risk]<=riskRank[riskMax];return cap&&risk})}
function status(env){return{ok:true,name:'afo-agent-gateway',version:env.AFO_AGENT_VERSION||VERSION,leadAgent,bindings:{d1:Boolean(env.AFO_DB),r2:Boolean(env.AFO_ARTIFACTS)},routes:['/status','/registry/tools','/registry/search','/registry/tools/:id','/agent/agent.afo.lead/invoke','/receipts'],persistence:'d1+r2',hardened:true,source:'github:worker/standalone/index.js'}}
async function invokeTool(env,call){const requestId=crypto.randomUUID();const tools=await dbTools(env);const tool=tools.find(t=>t.id===call.toolId);if(!tool){await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose||'',status:'failed',input:call.input,error:'tool_not_found'});throw new Error('tool_not_found')}if(!call.purpose||String(call.purpose).trim().length<3){await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose||'',status:'denied',input:call.input,error:'purpose_required'});throw new Error('purpose_required')}if(riskRank[tool.risk]>riskRank[leadAgent.maxRisk]){await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose,status:'denied',input:call.input,error:'risk_denied'});throw new Error('risk_denied')}let output;if(tool.id==='registry.search'){output={matches:searchTools(tools,call.input||{})}}else if(tool.id==='cloudflare.worker.deployPlan'){const workerName=call.input?.workerName||'afo-agent-gateway';output={workerName,steps:['load tool manifests from D1','bind Durable Object session state','bind D1 registry index','bind R2 receipt and artifact storage','route tool calls through policy gateway','write receipts to D1 and R2']}}else if(tool.id==='afo.agent.status'){output=status(env)}else{throw new Error('handler_not_found')}await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose,status:'executed',input:call.input,output});return output}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method==='GET'&&(url.pathname==='/'||url.pathname==='/status'))return json(status(env));if(request.method==='GET'&&url.pathname==='/registry/tools')return json({ok:true,tools:await dbTools(env)});if(request.method==='POST'&&url.pathname==='/registry/search'){const body=await readJson(request);return json({ok:true,tools:searchTools(await dbTools(env),body)})}const inspect=url.pathname.match(/^\/registry\/tools\/([^/]+)$/);if(request.method==='GET'&&inspect){const tool=(await dbTools(env)).find(t=>t.id===decodeURIComponent(inspect[1]));return tool?json({ok:true,tool}):json({ok:false,error:'tool_not_found'},{status:404})}const invoke=url.pathname.match(/^\/agent\/([^/]+)\/invoke$/);if(request.method==='POST'&&invoke){const body=await readJson(request);try{const output=await invokeTool(env,body);return json({ok:true,output,receipts:await dbReceipts(env)})}catch(e){return json({ok:false,error:e.message||String(e),receipts:await dbReceipts(env)},{status:400})}}if(request.method==='GET'&&url.pathname==='/receipts')return json({ok:true,receipts:await dbReceipts(env)});return json({ok:false,error:'not_found'},{status:404})}};
