const VERSION='0.2.0';
const riskRank={read:1,network:2,write:3,money:4,destructive:5};
const roleRank={public:0,read:1,operator:2,admin:3,owner:4};
const leadAgent={id:'agent.afo.lead',name:'AFO Lead Agent',mission:'Safe tool discovery, policy checks, approval gates, execution, and receipts.',allowedEnvironments:['local','cloudflare','github','browser','container','mcp','worker'],maxRisk:'write',requiredReceipts:true};
const tools=[
{id:'registry.search',name:'RegistrySearch',description:'Search the live AFO tool registry for tools and child agents by capability.',capabilities:['discover tools','search tool registry','find child agents','list capabilities'],permissions:['registry:read'],environment:'worker',risk:'read',version:VERSION,inputSchema:'capability:string,riskMax?:ToolRisk',outputSchema:'matches:ToolManifest[]',requiredRole:'public'},
{id:'registry.inspect',name:'RegistryInspect',description:'Inspect one tool manifest by id.',capabilities:['inspect tool','read tool manifest','explain capability'],permissions:['registry:read'],environment:'worker',risk:'read',version:VERSION,inputSchema:'toolId:string',outputSchema:'tool:ToolManifest',requiredRole:'public'},
{id:'agent.invoke',name:'AgentInvoke',description:'Invoke an allowed AFO.Agent tool through the policy and receipt gateway.',capabilities:['invoke tool','run agent tool','write receipt'],permissions:['agent:invoke','receipts:write'],environment:'worker',risk:'write',version:VERSION,inputSchema:'toolId:string,purpose:string,input:object',outputSchema:'output:any,receipts:Receipt[]',requiredRole:'operator'},
{id:'receipts.list',name:'ReceiptsList',description:'List recent AFO.Agent execution and sync receipts.',capabilities:['list receipts','audit agent activity','view ledger'],permissions:['receipts:read'],environment:'worker',risk:'read',version:VERSION,inputSchema:'limit?:number',outputSchema:'receipts:Receipt[]',requiredRole:'operator'},
{id:'github.repo.inspect',name:'GitHubRepoInspect',description:'Read safe metadata for a GitHub repository.',capabilities:['inspect github repo','read repository metadata','github read'],permissions:['github:read'],environment:'github',risk:'read',version:VERSION,inputSchema:'owner:string,repo:string',outputSchema:'repository metadata object',requiredRole:'read'},
{id:'github.file.read',name:'GitHubFileRead',description:'Read one UTF-8 file from GitHub through the configured GitHub API token.',capabilities:['read github file','inspect source file','github code read'],permissions:['github:read'],environment:'github',risk:'read',version:VERSION,inputSchema:'owner:string,repo:string,path:string,ref?:string',outputSchema:'file content metadata',requiredRole:'read'},
{id:'github.workflow.runs',name:'GitHubWorkflowRuns',description:'Read recent GitHub Actions workflow runs for a repository.',capabilities:['read github actions','inspect workflow runs','ci status'],permissions:['github:read'],environment:'github',risk:'read',version:VERSION,inputSchema:'owner:string,repo:string,limit?:number',outputSchema:'workflow run summaries',requiredRole:'read'},
{id:'cloudflare.workers.list',name:'CloudflareWorkersList',description:'List Cloudflare Workers visible to the configured Cloudflare API token.',capabilities:['list cloudflare workers','inspect worker inventory','cloudflare read'],permissions:['cloudflare:read'],environment:'cloudflare',risk:'read',version:VERSION,inputSchema:'{}',outputSchema:'workers[]',requiredRole:'read'},
{id:'cloudflare.worker.inspect',name:'CloudflareWorkerInspect',description:'Read Cloudflare Worker settings and binding names/types without exposing secret values.',capabilities:['inspect cloudflare worker','read worker settings','inspect bindings'],permissions:['cloudflare:read'],environment:'cloudflare',risk:'read',version:VERSION,inputSchema:'scriptName:string',outputSchema:'worker settings object',requiredRole:'read'},
{id:'cloudflare.d1.tables',name:'CloudflareD1Tables',description:'List tables for the configured or supplied Cloudflare D1 database.',capabilities:['inspect d1 database','list d1 tables','cloudflare d1 read'],permissions:['cloudflare:read','d1:read'],environment:'cloudflare',risk:'read',version:VERSION,inputSchema:'databaseId?:string,databaseName?:string',outputSchema:'tables[]',requiredRole:'read'},
{id:'approvals.request',name:'ApprovalsRequest',description:'Create a pending approval for a write, money, or destructive tool call.',capabilities:['request approval','approval gate','write approval record'],permissions:['approvals:write'],environment:'worker',risk:'write',version:VERSION,inputSchema:'toolId:string,purpose:string,input:object',outputSchema:'approval object',requiredRole:'operator'},
{id:'approvals.list',name:'ApprovalsList',description:'List pending or recent approval records.',capabilities:['list approvals','review pending actions','approval queue'],permissions:['approvals:read'],environment:'worker',risk:'read',version:VERSION,inputSchema:'status?:string,limit?:number',outputSchema:'approvals[]',requiredRole:'operator'},
{id:'approvals.decide',name:'ApprovalsDecide',description:'Approve or reject a pending approval record.',capabilities:['approve action','reject action','human approval'],permissions:['approvals:decide'],environment:'worker',risk:'write',version:VERSION,inputSchema:'approvalId:string,decision:approved|rejected,reason:string',outputSchema:'approval object',requiredRole:'owner'},
{id:'cloudflare.worker.deployPlan',name:'CloudflareWorkerDeployPlan',description:'Create a safe deployment plan for a Cloudflare Worker without deploying it.',capabilities:['plan cloudflare worker','edge worker planning','deployment planning'],permissions:['cloudflare:plan'],environment:'cloudflare',risk:'read',version:VERSION,inputSchema:'workerName:string,purpose:string',outputSchema:'workerName:string,steps:string[]',requiredRole:'public'},
{id:'cloudflare.worker.deployApply',name:'CloudflareWorkerDeployApply',description:'Approval-gated write scaffold for a future Cloudflare Worker deploy apply action.',capabilities:['apply cloudflare worker deploy','approval gated deploy','write worker deployment'],permissions:['cloudflare:write','approvals:required'],environment:'cloudflare',risk:'write',version:VERSION,inputSchema:'approvalId:string,workerName:string,sourceRef?:string',outputSchema:'deployment status object',requiredRole:'operator',requiresApproval:true},
{id:'afo.agent.status',name:'AfoAgentStatus',description:'Return AFO.Agent gateway status and runtime shape.',capabilities:['agent status','gateway status','health check'],permissions:['agent:read'],environment:'worker',risk:'read',version:VERSION,inputSchema:'{}',outputSchema:'status object',requiredRole:'public'}
];
const mcpTools=tools.map(t=>({name:t.id,description:t.description,inputSchema:inputSchemaFor(t.id)}));
function inputSchemaFor(name){const schemas={
'registry.search':{type:'object',properties:{capability:{type:'string'},riskMax:{type:'string',enum:['read','network','write','money','destructive']}},required:['capability']},
'registry.inspect':{type:'object',properties:{toolId:{type:'string'}},required:['toolId']},
'agent.invoke':{type:'object',properties:{toolId:{type:'string'},purpose:{type:'string'},input:{type:'object'}},required:['toolId','purpose']},
'receipts.list':{type:'object',properties:{limit:{type:'number'}},required:[]},
'github.repo.inspect':{type:'object',properties:{owner:{type:'string'},repo:{type:'string'}},required:['owner','repo']},
'github.file.read':{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},path:{type:'string'},ref:{type:'string'}},required:['owner','repo','path']},
'github.workflow.runs':{type:'object',properties:{owner:{type:'string'},repo:{type:'string'},limit:{type:'number'}},required:['owner','repo']},
'cloudflare.workers.list':{type:'object',properties:{},required:[]},
'cloudflare.worker.inspect':{type:'object',properties:{scriptName:{type:'string'}},required:['scriptName']},
'cloudflare.d1.tables':{type:'object',properties:{databaseId:{type:'string'},databaseName:{type:'string'}},required:[]},
'approvals.request':{type:'object',properties:{toolId:{type:'string'},purpose:{type:'string'},input:{type:'object'}},required:['toolId','purpose']},
'approvals.list':{type:'object',properties:{status:{type:'string'},limit:{type:'number'}},required:[]},
'approvals.decide':{type:'object',properties:{approvalId:{type:'string'},decision:{type:'string',enum:['approved','rejected']},reason:{type:'string'}},required:['approvalId','decision']},
'cloudflare.worker.deployPlan':{type:'object',properties:{workerName:{type:'string'},purpose:{type:'string'}},required:['workerName']},
'cloudflare.worker.deployApply':{type:'object',properties:{approvalId:{type:'string'},workerName:{type:'string'},sourceRef:{type:'string'}},required:['approvalId','workerName']},
'afo.agent.status':{type:'object',properties:{},required:[]}
};return schemas[name]||{type:'object',properties:{},required:[]}}
function cors(){return{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-afo-token,x-afo-role'}}
function json(data,init={}){return new Response(JSON.stringify(data,null,2),{...init,headers:{'content-type':'application/json; charset=utf-8',...cors(),...(init.headers||{})}})}
async function readJson(request){try{return await request.json()}catch{return {}}}
function safeInt(n,def=50,max=200){return Math.max(1,Math.min(Number(n)||def,max))}
function tokenFromRequest(request){const auth=request.headers.get('authorization')||'';if(auth.toLowerCase().startsWith('bearer '))return auth.slice(7).trim();return request.headers.get('x-afo-token')||request.headers.get('x-afo-admin-token')||''}
function roleTokens(env){return{read:env.AFO_AGENT_READ_TOKEN||'',operator:env.AFO_AGENT_OPERATOR_TOKEN||'',owner:env.AFO_AGENT_OWNER_TOKEN||'',admin:env.AFO_AGENT_ADMIN_TOKEN||''}}
function roleFromRequest(request,env){const token=tokenFromRequest(request);const tokens=roleTokens(env);if(tokens.admin&&token===tokens.admin)return'admin';if(tokens.owner&&token===tokens.owner)return'owner';if(tokens.operator&&token===tokens.operator)return'operator';if(tokens.read&&token===tokens.read)return'read';return'public'}
function hasRole(actual,required){return roleRank[actual]>=roleRank[required||'public']||actual==='admin'}
function requireRole(request,env,required){const role=roleFromRequest(request,env);if(hasRole(role,required))return{ok:true,role};return{ok:false,role,response:json({ok:false,error:'role_required',requiredRole:required,actualRole:role},{status:401})}}
function redactHeaders(h){const out={};for(const [k,v] of h.entries()){out[k]=k.toLowerCase().includes('authorization')||k.toLowerCase().includes('token')?'[redacted]':v}return out}
async function dbTools(env){if(!env.AFO_DB)return tools;try{const res=await env.AFO_DB.prepare('SELECT manifest_json FROM tools ORDER BY id').all();const rows=res.results||[];if(!rows.length)return tools;const fromDb=rows.map(r=>JSON.parse(r.manifest_json));const byId=new Map([...tools,...fromDb].map(t=>[t.id,t]));return [...byId.values()].sort((a,b)=>a.id.localeCompare(b.id))}catch{return tools}}
async function dbReceipts(env,limit=50){if(!env.AFO_DB)return[];try{const safeLimit=safeInt(limit);const res=await env.AFO_DB.prepare('SELECT * FROM receipts ORDER BY created_at DESC LIMIT ?').bind(safeLimit).all();return res.results||[]}catch{return[]}}
async function writeReceipt(env,item){const receipt={id:crypto.randomUUID(),requestId:item.requestId||crypto.randomUUID(),agentId:item.agentId||leadAgent.id,toolId:item.toolId,purpose:item.purpose||'',status:item.status,reason:item.reason||null,role:item.role||null,input:item.input??null,output:item.output??null,error:item.error||null,createdAt:new Date().toISOString()};if(env.AFO_DB){await env.AFO_DB.prepare('INSERT INTO receipts (id,request_id,agent_id,tool_id,purpose,status,reason,input_json,output_json,error,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(receipt.id,receipt.requestId,receipt.agentId,receipt.toolId,receipt.purpose,receipt.status,receipt.reason,JSON.stringify(receipt.input),JSON.stringify(receipt.output),receipt.error,receipt.createdAt).run()}if(env.AFO_ARTIFACTS){await env.AFO_ARTIFACTS.put(`receipts/${receipt.createdAt.slice(0,10)}/${receipt.id}.json`,JSON.stringify(receipt,null,2),{httpMetadata:{contentType:'application/json'}})}return receipt}
function searchTools(toolList,query={}){const capability=String(query.capability||'').toLowerCase();const riskMax=query.riskMax;return toolList.filter(t=>{const cap=!capability||t.name.toLowerCase().includes(capability)||t.description.toLowerCase().includes(capability)||(t.capabilities||[]).some(c=>c.toLowerCase().includes(capability));const risk=!riskMax||riskRank[t.risk]<=riskRank[riskMax];return cap&&risk})}
function status(env){return{ok:true,name:'afo-agent-gateway',version:env.AFO_AGENT_VERSION||VERSION,leadAgent,bindings:{d1:Boolean(env.AFO_DB),r2:Boolean(env.AFO_ARTIFACTS),githubToken:Boolean(env.GITHUB_TOKEN),cfToken:Boolean(env.CF_API_TOKEN),cfAccount:Boolean(env.CF_ACCOUNT_ID),readToken:Boolean(env.AFO_AGENT_READ_TOKEN),operatorToken:Boolean(env.AFO_AGENT_OPERATOR_TOKEN),ownerToken:Boolean(env.AFO_AGENT_OWNER_TOKEN),adminToken:Boolean(env.AFO_AGENT_ADMIN_TOKEN)},routes:['/status','/registry/tools','/registry/search','/registry/tools/:id','/agent/agent.afo.lead/invoke','/receipts','/approvals','/mcp','/openapi.json'],persistence:'d1+r2',hardened:true,auth:'role tokens',approvalGates:true,source:'github:worker/standalone/index.js'}}
async function gh(env,path){if(!env.GITHUB_TOKEN)throw new Error('github_token_missing');const res=await fetch(`https://api.github.com${path}`,{headers:{authorization:`Bearer ${env.GITHUB_TOKEN}`,'user-agent':'afo-agent-gateway','accept':'application/vnd.github+json'}});const text=await res.text();let data;try{data=JSON.parse(text)}catch{data={text}}if(!res.ok)throw new Error(`github_${res.status}:${data.message||text.slice(0,120)}`);return data}
async function cf(env,path){if(!env.CF_API_TOKEN)throw new Error('cf_api_token_missing');const account=env.CF_ACCOUNT_ID;if(!account)throw new Error('cf_account_id_missing');const full=path.replaceAll('{account_id}',account);const res=await fetch(`https://api.cloudflare.com/client/v4${full}`,{headers:{authorization:`Bearer ${env.CF_API_TOKEN}`,'content-type':'application/json'}});const data=await res.json().catch(()=>({}));if(!res.ok||data.success===false)throw new Error(`cloudflare_${res.status}:${JSON.stringify(data.errors||data)}`);return data}
async function approvalsTableReady(env){if(!env.AFO_DB)return false;try{await env.AFO_DB.prepare('SELECT id FROM approvals LIMIT 1').all();return true}catch{return false}}
async function createApproval(env,args,role){const now=new Date().toISOString();const approval={id:crypto.randomUUID(),request_id:crypto.randomUUID(),agent_id:leadAgent.id,tool_id:args.toolId,purpose:args.purpose,input_json:JSON.stringify(args.input??null),status:'pending',requested_by:role,decided_by:null,decision_reason:null,created_at:now,decided_at:null};if(!env.AFO_DB)throw new Error('d1_missing');if(!(await approvalsTableReady(env)))throw new Error('approvals_table_missing');await env.AFO_DB.prepare('INSERT INTO approvals (id,request_id,agent_id,tool_id,purpose,input_json,status,requested_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(approval.id,approval.request_id,approval.agent_id,approval.tool_id,approval.purpose,approval.input_json,approval.status,approval.requested_by,approval.created_at).run();return approval}
async function listApprovals(env,args){if(!env.AFO_DB)throw new Error('d1_missing');if(!(await approvalsTableReady(env)))return[];const limit=safeInt(args.limit,25,100);if(args.status){const res=await env.AFO_DB.prepare('SELECT * FROM approvals WHERE status=? ORDER BY created_at DESC LIMIT ?').bind(args.status,limit).all();return res.results||[]}const res=await env.AFO_DB.prepare('SELECT * FROM approvals ORDER BY created_at DESC LIMIT ?').bind(limit).all();return res.results||[]}
async function decideApproval(env,args,role){if(!env.AFO_DB)throw new Error('d1_missing');if(!(await approvalsTableReady(env)))throw new Error('approvals_table_missing');const decision=args.decision==='approved'?'approved':'rejected';const now=new Date().toISOString();await env.AFO_DB.prepare('UPDATE approvals SET status=?,decided_by=?,decision_reason=?,decided_at=? WHERE id=? AND status="pending"').bind(decision,role,args.reason||'',now,args.approvalId).run();const res=await env.AFO_DB.prepare('SELECT * FROM approvals WHERE id=?').bind(args.approvalId).first();if(!res)throw new Error('approval_not_found');return res}
async function requireApproved(env,approvalId,toolId){if(!env.AFO_DB)throw new Error('d1_missing');if(!(await approvalsTableReady(env)))throw new Error('approvals_table_missing');const row=await env.AFO_DB.prepare('SELECT * FROM approvals WHERE id=?').bind(approvalId).first();if(!row)throw new Error('approval_not_found');if(row.tool_id!==toolId)throw new Error('approval_tool_mismatch');if(row.status!=='approved')throw new Error('approval_not_approved');return row}
async function invokeTool(env,call,role){const requestId=crypto.randomUUID();const toolList=await dbTools(env);const tool=toolList.find(t=>t.id===call.toolId);if(!tool){await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose||'',status:'failed',role,input:call.input,error:'tool_not_found'});throw new Error('tool_not_found')}if(!hasRole(role,tool.requiredRole||'public')){await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose||'',status:'denied',role,input:call.input,error:'role_denied'});throw new Error(`role_denied:${tool.requiredRole||'public'}`)}if(!call.purpose||String(call.purpose).trim().length<3){await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose||'',status:'denied',role,input:call.input,error:'purpose_required'});throw new Error('purpose_required')}if(riskRank[tool.risk]>riskRank[leadAgent.maxRisk]){await writeReceipt(env,{requestId,toolId:call.toolId,purpose:call.purpose,status:'denied',role,input:call.input,error:'risk_denied'});throw new Error('risk_denied')}let output;const input=call.input||{};
if(tool.id==='registry.search')output={matches:searchTools(toolList,input)};
else if(tool.id==='registry.inspect'){const found=toolList.find(t=>t.id===input.toolId);if(!found)throw new Error('tool_not_found');output={tool:found}}
else if(tool.id==='receipts.list')output={receipts:await dbReceipts(env,input.limit||50)};
else if(tool.id==='afo.agent.status')output=status(env);
else if(tool.id==='github.repo.inspect'){const r=await gh(env,`/repos/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.repo)}`);output={repository:{id:r.id,full_name:r.full_name,private:r.private,default_branch:r.default_branch,html_url:r.html_url,updated_at:r.updated_at,pushed_at:r.pushed_at,visibility:r.visibility}}}
else if(tool.id==='github.file.read'){const ref=input.ref?`?ref=${encodeURIComponent(input.ref)}`:'';const f=await gh(env,`/repos/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.repo)}/contents/${input.path.split('/').map(encodeURIComponent).join('/')}${ref}`);const content=f.encoding==='base64'?atob(String(f.content||'').replace(/\s/g,'')):f.content;output={path:f.path,sha:f.sha,size:f.size,html_url:f.html_url,content}}
else if(tool.id==='github.workflow.runs'){const r=await gh(env,`/repos/${encodeURIComponent(input.owner)}/${encodeURIComponent(input.repo)}/actions/runs?per_page=${safeInt(input.limit,10,30)}`);output={total_count:r.total_count,runs:(r.workflow_runs||[]).map(x=>({id:x.id,name:x.name,status:x.status,conclusion:x.conclusion,head_branch:x.head_branch,head_sha:x.head_sha,run_started_at:x.run_started_at,html_url:x.html_url}))}}
else if(tool.id==='cloudflare.workers.list'){const r=await cf(env,'/accounts/{account_id}/workers/scripts');output={workers:(r.result||[]).map(w=>({id:w.id,created_on:w.created_on,modified_on:w.modified_on,usage_model:w.usage_model,compatibility_date:w.compatibility_date}))}}
else if(tool.id==='cloudflare.worker.inspect'){const r=await cf(env,`/accounts/{account_id}/workers/scripts/${encodeURIComponent(input.scriptName)}/settings`);output={settings:r.result}}
else if(tool.id==='cloudflare.d1.tables'){const dbid=input.databaseId||env.AFO_AGENT_D1_DATABASE_ID;if(!dbid)throw new Error('d1_database_id_missing');const r=await cf(env,`/accounts/{account_id}/d1/database/${encodeURIComponent(dbid)}/query`);output={note:'D1 direct query endpoint requires POST in Cloudflare API; use Cloudflare MCP query tool for live table reads.',databaseId:dbid,raw:r}}
else if(tool.id==='approvals.request')output={approval:await createApproval(env,input,role)};
else if(tool.id==='approvals.list')output={approvals:await listApprovals(env,input)};
else if(tool.id==='approvals.decide')output={approval:await decideApproval(env,input,role)};
else if(tool.id==='cloudflare.worker.deployPlan'){const workerName=input.workerName||'afo-agent-gateway';output={workerName,steps:['inspect current worker bindings','read GitHub source ref','create approval request for deployApply','verify approval status','deploy with preserve-bindings transport only','smoke test status, registry, mcp, receipts','write D1 and R2 receipts']}}
else if(tool.id==='cloudflare.worker.deployApply'){await requireApproved(env,input.approvalId,tool.id);output={status:'approved_but_not_executed',reason:'deployApply is a safety scaffold; use the Cloudflare preserve-bindings MCP for actual deployment.',workerName:input.workerName,sourceRef:input.sourceRef||null}}
else throw new Error('handler_not_found');
const receipt=await writeReceipt(env,{requestId,toolId:tool.id,purpose:call.purpose,status:'executed',role,input,output});return{output,receipt}}
function openApiSchema(){return{openapi:'3.1.0',info:{title:'AFO.Agent Gateway',version:VERSION,description:'Role-gated AFO.Agent gateway for ChatGPT Actions and MCP.'},servers:[{url:'https://afo-agent-gateway.jaredtechfit.workers.dev'}],components:{securitySchemes:{AFOBearer:{type:'http',scheme:'bearer'}}},paths:{'/status':{get:{operationId:'getStatus',summary:'Get status',responses:{'200':{description:'Status'}}}},'/registry/search':{post:{operationId:'searchRegistry',summary:'Search tools',requestBody:{required:true,content:{'application/json':{schema:inputSchemaFor('registry.search')}}},responses:{'200':{description:'Search results'}}}},'/registry/tools/{toolId}':{get:{operationId:'inspectTool',summary:'Inspect tool',parameters:[{name:'toolId',in:'path',required:true,schema:{type:'string'}}],responses:{'200':{description:'Tool manifest'}}}},'/agent/agent.afo.lead/invoke':{post:{operationId:'invokeLeadAgent',summary:'Invoke a role-gated tool',security:[{AFOBearer:[]}],requestBody:{required:true,content:{'application/json':{schema:inputSchemaFor('agent.invoke')}}},responses:{'200':{description:'Invocation result'},'401':{description:'Role token required'}}}},'/receipts':{get:{operationId:'listReceipts',summary:'List receipts',security:[{AFOBearer:[]}],responses:{'200':{description:'Receipts'}}}},'/mcp':{get:{operationId:'getMcpInfo',summary:'Get MCP information',responses:{'200':{description:'MCP capabilities'}}},post:{operationId:'mcpRpc',summary:'JSON-RPC MCP endpoint',responses:{'200':{description:'MCP JSON-RPC response'}}}}}}}
async function handleMcp(request,env){if(request.method==='GET')return json({ok:true,protocol:'mcp',serverInfo:{name:'afo-agent-gateway',version:VERSION},capabilities:{tools:{listChanged:false}},tools:mcpTools});const body=await readJson(request);const id=body.id??null;try{if(body.method==='initialize')return json({jsonrpc:'2.0',id,result:{protocolVersion:'2024-11-05',capabilities:{tools:{listChanged:false}},serverInfo:{name:'afo-agent-gateway',version:VERSION}}});if(body.method==='tools/list')return json({jsonrpc:'2.0',id,result:{tools:mcpTools}});if(body.method==='tools/call'){const name=body.params?.name;const args=body.params?.arguments||{};let result;if(name==='agent.invoke'){const auth=requireRole(request,env,'operator');if(!auth.ok)return auth.response;result=await invokeTool(env,args,auth.role)}else{const role=roleFromRequest(request,env);result=await invokeTool(env,{toolId:name,purpose:`MCP call ${name}`,input:args},role)}return json({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(result,null,2)}]}})}return json({jsonrpc:'2.0',id,error:{code:-32601,message:'method_not_found'}})}catch(e){return json({jsonrpc:'2.0',id,error:{code:-32000,message:e.message||String(e)}})}}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{headers:cors()});if(request.method==='GET'&&(url.pathname==='/'||url.pathname==='/status'))return json(status(env));if(request.method==='GET'&&(url.pathname==='/openapi.json'||url.pathname==='/.well-known/openapi.json'||url.pathname==='/actions/openapi.json'))return json(openApiSchema());if(url.pathname==='/mcp')return handleMcp(request,env);if(request.method==='GET'&&url.pathname==='/registry/tools')return json({ok:true,tools:await dbTools(env)});if(request.method==='POST'&&url.pathname==='/registry/search'){const body=await readJson(request);return json({ok:true,tools:searchTools(await dbTools(env),body)})}const inspect=url.pathname.match(/^\/registry\/tools\/([^/]+)$/);if(request.method==='GET'&&inspect){const tool=(await dbTools(env)).find(t=>t.id===decodeURIComponent(inspect[1]));return tool?json({ok:true,tool}):json({ok:false,error:'tool_not_found'},{status:404})}const invoke=url.pathname.match(/^\/agent\/([^/]+)\/invoke$/);if(request.method==='POST'&&invoke){const body=await readJson(request);const toolList=await dbTools(env);const requestedTool=toolList.find(t=>t.id===body.toolId);const required=requestedTool?.requiredRole||'operator';const auth=requireRole(request,env,required);if(!auth.ok)return auth.response;try{const result=await invokeTool(env,body,auth.role);return json({ok:true,...result,receipts:await dbReceipts(env,10)})}catch(e){return json({ok:false,error:e.message||String(e),receipts:await dbReceipts(env,10)},{status:400})}}if(request.method==='GET'&&url.pathname==='/receipts'){const auth=requireRole(request,env,'operator');if(!auth.ok)return auth.response;return json({ok:true,receipts:await dbReceipts(env,url.searchParams.get('limit')||50)})}if(request.method==='GET'&&url.pathname==='/approvals'){const auth=requireRole(request,env,'operator');if(!auth.ok)return auth.response;try{return json({ok:true,approvals:await listApprovals(env,{status:url.searchParams.get('status')||undefined,limit:url.searchParams.get('limit')||25})})}catch(e){return json({ok:false,error:e.message||String(e)},{status:400})}}if(url.pathname.startsWith('/admin/')){const auth=requireRole(request,env,'admin');if(!auth.ok)return auth.response;return json({ok:true,admin:true,status:status(env),receipts:await dbReceipts(env,25),headers:redactHeaders(request.headers)})}return json({ok:false,error:'not_found'},{status:404})}};
